# Generated by Django 5.2.3 on 2025-06-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_imagen_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
